config/routes.rb
Rails.application.routes.draw do
 
  devise_for :users
  resources :users, only: [:show, :update]
  resources :topics do
    resources :bookmarks, except: [:index] do
      resources :favorites, only: [:create, :destroy]
    end
  end
  root to: 'welcome#index'
  get 'about' => 'welcome#about'
  post :incoming, to: 'incoming#create'
end

app/models/bookmark.rb
class Bookmark < ActiveRecord::Base
  belongs_to :user
  belongs_to :topic
  has_many :favorites, dependent: :destroy

  default_scope { order('created_at DESC') }
end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  belongs_to :bookmark
  belongs_to :user
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  has_many :bookmarks
  has_many :bookmarks, dependent: :destroy
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  has_many :bookmarks
  has_many :favorites, dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  def favorited(bookmark)
    self.favorites.where(bookmark_id: bookmark.id).first
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  # def index
  #   # optional because the topic show is already showing all the booksmarks for a topic
  #   @bookmarks = Bookmark.all
  # end

  def new
    @topic = Topic.find(params[:topic_id])
    @bookmark = Bookmark.new
  end

   def create
    @topic = Topic.find(params[:topic_id])
    @bookmark = current_user.bookmarks.build(params.require(:bookmark).permit(:url))
    @bookmark.topic = @topic

    if @bookmark.save
      redirect_to @topic
    else
      render :new
    end
  end

  def destroy
    @topic = Topic.find(params[:topic_id])
    @bookmark = Bookmark.find(params[:id])

    url = @bookmark.url
    if @bookmark.destroy
      flash[:notice] = "\"#{url}\" was deleted successfully."
      redirect_to @topic
    else
      flash[:error] = "There was an error deleting the bookmark."
      render :show
    end
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    @topic = Topic.find(params[:topic_id])
    @bookmark = @topic.bookmarks.find(params[:bookmark_id])
    favorite = current_user.favorites.build(bookmark: @bookmark)

    if favorite.save
      flash[:notice] = "Favorited bookmark"
    else
      flash[:error] = "Unable to add favorite. Please try again."
    end
    redirect_to @topic
  end

  def destroy
  @topic = Topic.find(params[:topic_id])
  @bookmark = @topic.bookmarks.find(params[:bookmark_id])
  favorite = current_user.favorites.find(params[:id])

    if favorite.destroy
      flash[:notice] = "Removed favorite."
    else
      flash[:error] = "Unable to remove favorite. Please try again."
    end
    redirect_to @topic
  end
end

app/controllers/incoming_controller.rb
class IncomingController < ApplicationController

  # http://stackoverflow.com/questions/1177863/how-do-i-ignore-the-authenticity-token-for-specific-actions-in-rails
  skip_before_filter :verify_authenticity_token, only: [:create]

  def create
    user = User.find_by_email(params[:sender])
    topic = Topic.find_by_name(params[:subject])
    url = params["body-plain"]

    if user.nil?
      user = User.new(
        email: params[:sender],
        password: Faker::Lorem.characters(10)
      )
      user.skip_confirmation!
      user.save
    end 

    if topic.nil?
      topic = Topic.new(name: params[:subject])
      topic.save
    end

    bookmark = user.bookmarks.build(url: url)
    bookmark.topic = topic
    bookmark.save

    # send an email to the admin

    head 200
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController

  def index
    @topics = Topic.all
    @topics = @topics.sort {|x, y| y.bookmarks.count <=> x.bookmarks.count }
    @favorite = Favorite.new
  end

  def show
    @topic = Topic.find(params[:id])
    @bookmarks = @topic.bookmarks
  end

  def new
    @topic = Topic.new
  end

   def create
    @topic = Topic.find_by_name(params[:name])
    unless @topic
      @topic = Topic.new(name: params[:name])
      @topic.save
    end
  end

def destroy
    @topic = Topic.find(params[:id])
    name = @topic.name

    if @topic.destroy
      flash[:notice] = "\"#{name}\" was deleted successfully."
      redirect_to topics_path
    else
      flash[:error] = "There was an error deleting the topic."
      render :show
    end
  end

  def edit
    @topic = Topic.find(params[:id])
  end

  def create
    @topic = Topic.new(topic_params)
    if @topic.save
      redirect_to @topic
    else
      render :new
    end
  end

  private
    def topic_params
      params.require(:topic).permit(:name)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def update
    if current_user.update_attributes(user_params)
      flash[:notice] = "User information updated"
      redirect_to edit_user_registration_path(current_user)
    else
      render "devise/registrations/edit"
    end
  end

  def show
    @user = User.find(params[:id])
    @bookmarks = @user.bookmarks
    @user_topics = current_user.bookmarks.map {|bookmark| bookmark.topic }.uniq
    @favorited_topics = current_user.favorites.map {|favorite| favorite.bookmark.topic}.uniq
    @topics = @user_topics + @favorited_topics

    @favorites = @user.favorites
  end

  def destroy
    @topic = Topic.find(params[:topic_id])
    @bookmark = @topic.bookmarks.find(params[:bookmark_id])
    @favorite = Favorite.find(params[:id])

    if @favorite.destroy
      redirect_to user_path(current_user)
    end
  end

  private

  def user_params
    params.require(:user).permit(:name)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/bookmarks/destroy.html.erb
<h1>Bookmarks#destroy</h1>
<p>Find me in app/views/bookmarks/destroy.html.erb</p>

app/views/bookmarks/index.html.erb
<h1>All Blocmarks</h1>
<% @bookmarks.each do |bookmark| %>
  <div class="media">
    <div class="media-body">
      <h5 class="media-heading">
        <%= link_to bookmark.url, bookmark.url %>
      </h5>
    </div>
  </div>
<% end %>

app/views/bookmarks/new.html.erb
 <%= form_for [@topic, @bookmark] do |f| %>
   <%= f.label :url %>
   <%= f.text_field :url %>

   <%= f.submit "Save" %>
 <% end %>

app/views/favorites/_favorite.html.erb
  <div class="favorite">
    <% if favorite = current_user.favorited(bookmark) %>
      <%= link_to [topic, bookmark, favorite], class: 'btn btn-danger', method: :delete do %>
        <i class="glyphicon glyphicon-star-empty"> </i>&nbsp; Unfavorite
      <% end %>
    <% else %>
      <%= link_to [topic, bookmark, Favorite.new], class: 'btn btn-primary', method: :bookmark do %>
        <i class="glyphicon glyphicon-star"> </i>&nbsp; Favorite
      <% end %>
    <% end %>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blocmarks</title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="container" id="wrapper">
      <ul class="nav nav-tabs">

          <li><%= link_to "Home",root_path %></li>
          <li><%= link_to "Blocmarks", topics_path %></li>
          <li><%= link_to "About", about_path %></li>

        <div class="pull-right user-info">
         <% if current_user %>
          Hello <%= link_to current_user.email, current_user %>!
          <%= link_to edit_user_registration_path, class: 'btn btn-primary btn-sm' do %>
            <span class="glyphicon glyphicon-user" title="User Profile"></span>
          <% end %>

          <%= link_to destroy_user_session_path, method: :delete, class: 'btn btn-primary btn-sm' do %>
            <span class="glyphicon glyphicon-log-out" title="Sign Out"></span>
          <% end %>
        <% else %>
         <%= link_to "Sign In", new_user_session_path %> or
         <%= link_to "Sign Up", new_user_registration_path %>
        <% end %>
        </div>
      </ul>

      <%= yield %>
    </div>
  </body>
</html>

app/views/topics/create.html.erb
<h1>Topics#create</h1>
<p>Find me in app/views/topics/create.html.erb</p>

app/views/topics/destroy.html.erb
<h1>Topics#destroy</h1>
<p>Find me in app/views/topics/destroy.html.erb</p>

app/views/topics/edit.html.erb
<h1>Edit Topic</h1>

<div class="row">
  <div class="col-md-4">
    <p>Guidelines for topics:</p>
    <ul>
      <li>Make sure the topic is appropriate.</li>
    </ul>
  </div>
  <div class="col-md-8">
    <%= form_for @topic do |f| %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control', placeholder: "Enter topic name" %>
      </div>
      </div>
      <%= f.submit "Save", class: 'btn btn-success' %>
    <% end %>
  </div>
</div>

app/views/topics/index.html.erb
<h1>Topics</h1>

<div class="row">
  <div class="col-md-8">
    <% @topics.each do |topic| %>
      <div class="media">
        <div class="media-body">
          <h4 class="media-heading">
            <%= link_to topic.name, topic %>
          </h4>
        </div>
      </div>
    <% end %>
  </div>
  <div class="col-md-4">
    <% if true %>
      <%= link_to "New Topic", new_topic_path, class: 'btn btn-success' %>
    <% end %>
  </div>
</div>

app/views/topics/new.html.erb
<h1>New Topic</h1>

<div class="row">
  <div class="col-md-4">
    <p>Guidelines for topics:</p>
    <ul>
      <li>Make sure the topic is appropriate.</li>

    </ul>
  </div>
  <div class="col-md-8">
    <%= form_for @topic do |f| %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control', placeholder: "Enter topic name" %>
      </div>
      <%= f.submit "Save", class: 'btn btn-success' %>
    <% end %>
  </div>
</div>

app/views/topics/show.html.erb
<h1><%= @topic.name %></h1>

<% if true %>
  <%= link_to "Edit Topic", edit_topic_path, class: 'btn btn-success' %>
<% end %>
<% if true %>
  <%= link_to "Delete Topic", @topic, method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete this topic?' } %>
<% end %>

<div class="row">
  <div class="col-md-8">
    <p class="lead"><%= @topic.name %></p>
    <% @bookmarks.each do |bookmark| %>
      <div class="media">
        <div class="media-body">
          <h4 class="media-heading">
            <%= link_to bookmark.url, bookmark.url %>
            <br>
             <%= render partial: 'favorites/favorite', locals: { topic: @topic, bookmark: bookmark } %>
             <br>
              <%= link_to "Delete Bookmark", [@topic, bookmark], method: :delete, class: 'btn btn-primary', data: { confirm: 'Are you sure you want to delete this topic?' } %>
          </h4>
        </div>
      </div>
    <% end %>
  </div>
    <div class="col-md-4">
      <%= link_to "New Bookmark", new_topic_bookmark_path(@topic), class: 'btn btn-success' %>
    </div>
  </div>
</div>

app/views/topics/update.html.erb
<h1>Topics#update</h1>
<p>Find me in app/views/topics/update.html.erb</p>

app/views/users/show.html.erb
<div class="row">
  <div class="col-md-8">
      <div class="media-body">
        <h1 class="media-heading"><%= @user.email %></h1>
          <h2><%= pluralize(@user.bookmarks.count, 'bookmark') %></h2>
        <% @user.bookmarks.each do |bookmark| %>
          <div class="media">
            <div class="media-body">
              <h4 class="media-heading">
                <%= link_to bookmark.url, bookmark.url %>
              </h4>
            </div>
          </div>
        <% end %>
          <h2><%= pluralize(@user.favorites.count, 'favorite') %></h2>
        <% @user.favorites.each do |favorite| %>
          <div class="media">
            <div class="media-body">
              <h4 class="media-heading">
                <%= link_to favorite.bookmark.url, favorite.bookmark.url %>
              </h4>
            </div>
          </div>
        <% end %>
      </div>
  </div>
</div>

app/views/welcome/about.html.erb
<h1>About Blocmarks</h1>
<p>Created by NPL</p>

app/views/welcome/index.html.erb
<br/>
<div class="jumbotron" id="banner">
  <h1>Blocmarks</h1>
  <p>Blocmarks allow you to bookmark URLs via email, browse other user's favorite bookmarks, and maintain a personal index of categorized bookmarks.</p>

  <p>
    <%= link_to "Sign In", new_user_session_path, class: 'btn btn-primary' %> or 
    <%= link_to "Sign Up", new_user_registration_path, class: 'btn btn-primary' %> today!
  </p>
</div>